### ISSUE TITLE
How to train it to achieve image removal image removal watermark?

### ISSUE THREAD

**Issue by ghost** [shivamsaboo17/Deep-Restore-PyTorch#2]
How to train it to achieve image removal image removal watermark?

**Comment by shivamsaboo17** [comment]
Sorry for the late reply. Try to use the L1 loss for text watermarks as mentioned in the original paper as the median is a correct statistic.

**Comment by vivekdeepquanty** [comment]
what is 'train-jpg/' in Train ??

**Comment by shivamsaboo17** [comment]
@vivekdeepquanty It is the path to training directory. This would change for you depending on where you have saved your dataset.
