### ISSUE TITLE
poisson noise de-noising

### ISSUE THREAD

**Issue by arjung128** [shivamsaboo17/Deep-Restore-PyTorch#3]
Hi, thanks for making this work open source!

I was wondering if you were able to implement poisson de-noising -- Is this something you are currently working on? 

Many other de-noisers seems to focus primarily on Gaussian de-noising and their architectures don't seem to do very well when trained on Poisson noise... just wondering if this is something you are working on / plan to implement in the future.

**Comment by shivamsaboo17** [comment]
Hi, I am not currently working on this. However feel free to open a PR if you are able to implement it. You may want to look at how the Poisson noise is added, in the official source code here: https://github.com/NVlabs/noise2noise/blob/c40a0481198bb524d0b70c2cc452f21bd7aec85c/train.py#L37
